# Generated by Django 4.2.1 on 2023-05-14 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissionalisa_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birthYear',
            new_name='birth_year',
        ),
    ]
