# Generated by Django 4.2.1 on 2023-05-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissionalisa_api', '0003_comentario_curso_mentor_sessao_usuario_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario',
            new_name='login',
        ),
    ]
